# Generated by Django 3.0.8 on 2020-09-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
